import Foundation

enum SystemProfilerDataType: String, CaseIterable, Sendable, Codable, Hashable {
    case parallelATA = "SPParallelATADataType"
    case universalAccess = "SPUniversalAccessDataType"
    case secureElement = "SPSecureElementDataType"
    case applications = "SPApplicationsDataType"
    case audio = "SPAudioDataType"
    case bluetooth = "SPBluetoothDataType"
    case camera = "SPCameraDataType"
    case cardReader = "SPCardReaderDataType"
    case iBridge = "SPiBridgeDataType"
    case developerTools = "SPDeveloperToolsDataType"
    case diagnostics = "SPDiagnosticsDataType"
    case disabledSoftware = "SPDisabledSoftwareDataType"
    case discBurning = "SPDiscBurningDataType"
    case ethernet = "SPEthernetDataType"
    case extensions = "SPExtensionsDataType"
    case fibreChannel = "SPFibreChannelDataType"
    case firewall = "SPFirewallDataType"
    case fonts = "SPFontsDataType"
    case frameworks = "SPFrameworksDataType"
    case displays = "SPDisplaysDataType"
    case hardware = "SPHardwareDataType"
    case installHistory = "SPInstallHistoryDataType"
    case international = "SPInternationalDataType"
    case networkLocation = "SPNetworkLocationDataType"
    case logs = "SPLogsDataType"
    case managedClient = "SPManagedClientDataType"
    case memory = "SPMemoryDataType"
    case nvme = "SPNVMeDataType"
    case network = "SPNetworkDataType"
    case pci = "SPPCIDataType"
    case parallelSCSI = "SPParallelSCSIDataType"
    case power = "SPPowerDataType"
    case preferencePanes = "SPPrefPaneDataType"
    case printerSoftware = "SPPrintersSoftwareDataType"
    case printers = "SPPrintersDataType"
    case configurationProfiles = "SPConfigurationProfileDataType"
    case rawCamera = "SPRawCameraDataType"
    case legacySoftware = "SPLegacySoftwareDataType"
    case sas = "SPSASDataType"
    case serialATA = "SPSerialATADataType"
    case spi = "SPSPIDataType"
    case smartCards = "SPSmartCardsDataType"
    case software = "SPSoftwareDataType"
    case startupItems = "SPStartupItemDataType"
    case storage = "SPStorageDataType"
    case syncServices = "SPSyncServicesDataType"
    case thunderbolt = "SPThunderboltDataType"
    case usb = "SPUSBHostDataType"
    case networkVolumes = "SPNetworkVolumeDataType"
    case wifi = "SPAirPortDataType"

    var title: String {
        switch self {
        case .parallelATA: "Parallel ATA"
        case .universalAccess: "Accessibility"
        case .secureElement: "Secure Element"
        case .applications: "Applications"
        case .audio: "Audio"
        case .bluetooth: "Bluetooth"
        case .camera: "Cameras"
        case .cardReader: "Card Readers"
        case .iBridge: "Apple Bridge"
        case .developerTools: "Developer Tools"
        case .diagnostics: "Diagnostics"
        case .disabledSoftware: "Disabled Software"
        case .discBurning: "Disc Burning"
        case .ethernet: "Ethernet"
        case .extensions: "Extensions"
        case .fibreChannel: "Fibre Channel"
        case .firewall: "Firewall"
        case .fonts: "Fonts"
        case .frameworks: "Frameworks"
        case .displays: "Graphics and Displays"
        case .hardware: "Hardware Overview"
        case .installHistory: "Install History"
        case .international: "Language and Region"
        case .networkLocation: "Network Locations"
        case .logs: "System Logs"
        case .managedClient: "Managed Client"
        case .memory: "Memory"
        case .nvme: "NVMExpress"
        case .network: "Network"
        case .pci: "PCI"
        case .parallelSCSI: "Parallel SCSI"
        case .power: "Power"
        case .preferencePanes: "Preference Panes"
        case .printerSoftware: "Printer Software"
        case .printers: "Printers"
        case .configurationProfiles: "Configuration Profiles"
        case .rawCamera: "RAW Camera Support"
        case .legacySoftware: "Legacy Software"
        case .sas: "SAS"
        case .serialATA: "Serial ATA"
        case .spi: "SPI"
        case .smartCards: "Smart Cards"
        case .software: "Software Overview"
        case .startupItems: "Startup Items"
        case .storage: "Storage"
        case .syncServices: "Sync Services"
        case .thunderbolt: "Thunderbolt and USB4"
        case .usb: "USB"
        case .networkVolumes: "Network Volumes"
        case .wifi: "Wi-Fi"
        }
    }
}
